### ISSUE TITLE
Traceback when run immediately after install

### ISSUE THREAD

**Issue by OddBloke** [twisted/towncrier#181]
```sh
$ mkvirtualenv test
...
$ pip install towncrier
...
$ towncrier
Loading template...
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/test/bin/towncrier", line 8, in <module>
    sys.exit(_main())
  File "/home/daniel/.virtualenvs/test/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/daniel/.virtualenvs/test/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/daniel/.virtualenvs/test/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daniel/.virtualenvs/test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/daniel/.virtualenvs/test/lib/python3.8/site-packages/towncrier/__init__.py", line 53, in _main
    return __main(
  File "/home/daniel/.virtualenvs/test/lib/python3.8/site-packages/towncrier/__init__.py", line 67, in __main
    if config["template"] is None:
TypeError: 'NoneType' object is not subscriptable
```

(This is running with Python 3.8 on the development release of Ubuntu, 20.04.)

**Comment by OddBloke** [comment]
Aha, immediately after filing this I realised there was an RC I could test, and this is fixed in towncrier-19.9.0rc1.
