### ISSUE TITLE
BUG towncrier `check` fails on gitlab CI

### ISSUE THREAD

**Issue by qequ** [twisted/towncrier#442]
I'm working with towncrier on a gitlab repo. Towncrier on local works fine and when using it with `check` command it finds the fragment correctly.
I've also added a job to a gitlab pipeline that checks the fragments when opening a merge request. The job looks like this

```created-fragment:
  stage: lint
  rules:
    - if: $CI_MERGE_REQUEST_ID
  before_script:
    - python -m pip install towncrier
  script:
    - git fetch --no-tags origin +refs/heads/$CI_DEFAULT_BRANCH:refs/remotes/origin/$CI_DEFAULT_BRANCH
    - python -m towncrier check --compare-with origin/$CI_DEFAULT_BRANCH --config towncrier_config.toml

```

when running that job towncrier fails with this output

```
git produced output while failing:
fatal: origin/main...HEAD: no merge base
Traceback (most recent call last):
  File "/usr/local/bin/towncrier", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/towncrier/check.py", line 50, in _main
    return __main(compare_with, directory, config)
  File "/usr/local/lib/python3.8/site-packages/towncrier/check.py", line 64, in __main
    _run(
  File "/usr/local/lib/python3.8/site-packages/towncrier/check.py", line 18, in _run
    return check_output(args, **kwargs)
  File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'diff', '--name-only', 'origin/main...']' returned non-zero exit status 128.
```

it seems to have issues finding the HEAD

**Comment by altendky** [comment]
When you clone your source is it cloning the entire history?  I know with the standard GitHub Actions checkout action it defaults to not getting any history.  This leaves git unable to do things with history such as the diff towncrier is trying to check to see if the branch is introducing any newsfragments.

I tried briefly here to recreate that particular message locally with a clone such as `git clone --depth 1 --branch add_3.10 git@github.com:altendky/qtrio` but only managed to get other error messages.  Not sure if my theory is wrong, or my git version just acts differently or...

**Comment by qequ** [comment]
by default I think gitlab CI doesn't get the complete history either. That's why I fetch the main branch to compare it with the branch
```
git fetch --no-tags origin +refs/heads/$CI_DEFAULT_BRANCH:refs/remotes/origin/$CI_DEFAULT_BRANCH
```  
but even with that towncrier still fails

**Comment by altendky** [comment]
Does that fetch you the history of the branch being built though?  Maybe add `git log --max-count 5 $CI_DEFAULT_BRANCH` and `git log --max-count 5 HEAD` and see what they show.

```console
$ git clone --depth 1 --branch add_3.10 git@github.com:altendky/qtrio
Cloning into 'qtrio'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 93 (delta 2), reused 42 (delta 0), pack-reused 0
Receiving objects: 100% (93/93), 68.06 KiB | 2.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
```

```console
$ cd qtrio
```

```console
$ git log add_3.10
commit 5aaa2b79bf6464cb310ebb610ddd319746a29b33 (grafted, HEAD -> add_3.10, origin/add_3.10)
Author: Kyle Altendorf <sda@fstab.net>
Date:   Mon Oct 11 22:54:44 2021 -0400

    PySide2 does not support 3.10 (again)
```

```console
$ git log origin/main
fatal: ambiguous argument 'origin/main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

```console
$ git fetch --no-tags origin +refs/heads/main:refs/remotes/origin/main
remote: Enumerating objects: 5341, done.
remote: Counting objects: 100% (5341/5341), done.
remote: Compressing objects: 100% (1593/1593), done.
remote: Total 5268 (delta 3715), reused 5000 (delta 3488), pack-reused 0
Receiving objects: 100% (5268/5268), 752.75 KiB | 932.00 KiB/s, done.
Resolving deltas: 100% (3715/3715), completed with 58 local objects.
From github.com:altendky/qtrio
 * [new branch]      main       -> origin/main
```

```console
$ git log --max-count 5 origin/main
commit 95269a6f1d193682fd5bf7c0072b4f71e6e5020f (origin/main)
Merge: 8acbe71 d0ad44e
Author: Kyle Altendorf <sda@fstab.net>
Date:   Thu Oct 13 11:38:34 2022 -0400

    Merge pull request #274 from altendky/release-v0.5.1
    
    Prepare release v0.5.1

commit d0ad44e4367857a4c4da2950dd660d84438c3b27
Author: Kyle Altendorf <sda@fstab.net>
Date:   Thu Oct 13 11:20:49 2022 -0400

    Update _version.py

commit 90c7f8afc03a00414475e97c443875cc86772e00
Author: Kyle Altendorf <sda@fstab.net>
Date:   Thu Oct 13 10:39:18 2022 -0400

    remove link to trio.MultiError from history

commit d1049e0bc56aafd25c400e3c1d1a3e550e2a1f23
Author: Kyle Altendorf <sda@fstab.net>
Date:   Thu Oct 13 10:36:27 2022 -0400

    update ignore and shift error from CI command to config

commit 3c04b9568772010c0bdf9596a1499dc4df35e638
Author: Kyle Altendorf <sda@fstab.net>
Date:   Thu Oct 13 09:58:25 2022 -0400

    ignore MultiError Deprecation
```

```console
$ git log add_3.10
commit 5aaa2b79bf6464cb310ebb610ddd319746a29b33 (grafted, HEAD -> add_3.10, origin/add_3.10)
Author: Kyle Altendorf <sda@fstab.net>
Date:   Mon Oct 11 22:54:44 2021 -0400

    PySide2 does not support 3.10 (again)
```

**Comment by altendky** [comment]
The GitHub checkout action has an option to do a full clone.  Maybe the GitLab tooling has an option as well.

**Comment by qequ** [comment]
yes, it gets the history correctly and continues failling

```
$ git fetch --no-tags origin +refs/heads/$CI_DEFAULT_BRANCH:refs/remotes/origin/$CI_DEFAULT_BRANCH
From https://gitlab.com/fproj/backoffice
 * [new branch]      main       -> origin/main

$ git log --max-count 5 origin/$CI_DEFAULT_BRANCH
commit f55d84563dc1e6540f75d822f0ae7e75d756df90
Author: Alvaro Frias <alvaro.frias@eclypsium.com>
Date:   Thu Sep 29 15:42:38 2022 +0000

commit 418eeed1d88d3b5f98530d08c030b2f8d881f653
Author: Alvaro Frias <alvaro.frias@eclypsium.com>
Date:   Wed Sep 28 21:06:05 2022 +0000

commit 47e7aab80b428ade673009b132de7047da17d349
Author: Alvaro Frias <alvaro.frias@eclypsium.com>
Date:   Fri Sep 23 23:41:38 2022 +0000

commit 4ed6ba278a2a66f81c6cc2efa3c7895fadfd387f
Author: Alvaro Frias <alvaro.frias@eclypsium.com>
Date:   Wed Sep 21 14:52:11 2022 +0000

commit dcbe016d0c3b3b3df394bc66f84700a0a4a10c13
Author: Alvaro Frias <alvaro.frias@eclypsium.com>
Date:   Tue Sep 20 20:36:56 2022 +0000


$ python -m towncrier check --compare-with origin/$CI_DEFAULT_BRANCH --config towncrier_enhancerizr.toml
git produced output while failing:
fatal: origin/main...HEAD: no merge base
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/towncrier/__main__.py", line 4, in <module>
    cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/towncrier/check.py", line 50, in _main
    return __main(compare_with, directory, config)
  File "/usr/local/lib/python3.8/site-packages/towncrier/check.py", line 64, in __main
    _run(
  File "/usr/local/lib/python3.8/site-packages/towncrier/check.py", line 18, in _run
    return check_output(args, **kwargs)
  File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'diff', '--name-only', 'origin/main...']' returned non-zero exit status 128.


```

**Comment by altendky** [comment]
What about the other relevant branch though?  `git log --max-count 5 HEAD`

**Comment by qequ** [comment]
yes, that too but keeps failling. I think it's some kind of issue with the CI, like this issue https://github.com/ros/rosdistro/issues/29964
```
$ git log --max-count 5 HEAD
commit c46fee3e9c2cfcb76878067bbdeee8b894bab9e5
Author: Alvaro Frias Garay <alvaro.frias@eclypsium.com>
Date:   Fri Oct 14 17:20:03 2022 -0300

    
    Signed-off-by: Alvaro Frias Garay <alvaro.frias@eclypsium.com>
commit 8fbade94ec7db05982fcb7abd8adacc63b0fe014
Author: Alvaro Frias Garay <alvaro.frias@eclypsium.com>
Date:   Fri Oct 14 16:57:42 2022 -0300

    
    Signed-off-by: Alvaro Frias Garay <alvaro.frias@eclypsium.com>
commit 1474398a4c30bf6fe3bed830351ef80231090192
Author: Alvaro Frias Garay <alvaro.frias@eclypsium.com>
Date:   Fri Oct 14 16:36:28 2022 -0300

    
    Signed-off-by: Alvaro Frias Garay <alvaro.frias@eclypsium.com>
commit dc98000b5b49fef47b9c8f292706dee023998c5d
Author: Alvaro Frias Garay <alvaro.frias@eclypsium.com>
Date:   Fri Oct 14 16:24:36 2022 -0300

    
    Signed-off-by: Alvaro Frias Garay <alvaro.frias@eclypsium.com>
commit eef1ed2589be2c6fbd58c1270fc890313a927829
Author: Alvaro Frias Garay <alvaro.frias@eclypsium.com>
Date:   Fri Oct 14 16:23:09 2022 -0300

```

**Comment by altendky** [comment]
Maybe drop the `--max-count 5` and see some more history.  Or pick a bigger number.  Or check what the default depth is for cloning.  Your link said it was 'fixed' by merging master into the branch.  That would make the merge base more recent and it would start working even with a small clone depth.  Or, use a bigger clone depth.

**Comment by qequ** [comment]
thanks @altendky for the answers, it was a problem with pipeline that couldn't figure it out. Maybe it was having wrong git data, I'm not sure. With other pipelines the check worked just fine
