### ISSUE TITLE
Other `{}` style directives for Markdown via MyST

### ISSUE THREAD

**Issue by ilan-gold** [twisted/towncrier#661]
Hello!  Would it be possible to allow other things inside `{}` instead of erroring out?  https://myst-parser.readthedocs.io/en/latest/syntax/typography.html uses these for various directives.  At the moment, for example, if I add `{small}` to my custom `title_format`, I get:

```python
Loading template...
Finding news fragments...
Rendering news fragments...
Traceback (most recent call last):
  File "/Users/ilangold/Projects/Theis/anndata/venv/bin/towncrier", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ilangold/Projects/Theis/anndata/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilangold/Projects/Theis/anndata/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ilangold/Projects/Theis/anndata/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilangold/Projects/Theis/anndata/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilangold/Projects/Theis/anndata/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilangold/Projects/Theis/anndata/venv/lib/python3.11/site-packages/towncrier/build.py", line 123, in _main
    return __main(
           ^^^^^^^
  File "/Users/ilangold/Projects/Theis/anndata/venv/lib/python3.11/site-packages/towncrier/build.py", line 231, in __main
    top_line = config.title_format.format(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'small'
```

Maybe a new key for ignoring these key errors?  I also couldn't get an escape character to work here

**Comment by adiroiban** [comment]
Hi Ilan. Thanks for the report.

towncrier only support RST and MD.
The RST and MD are rendered using Jinja2.

I am not familiar with MyST.

Feel free to send a PR implemeting supoprt for MyST.

As long as the new functinality is documented, has automated tests, the code is easy to read, and does not introduce any regression, we can review the PR and have it merged.

**Comment by adiroiban** [comment]
I now see that the title_format is rendered using Python string `.format()` ... this is a bit of a mess :(

--------

You can have a custom jinja2 template and use `.lower()` to have lowercase. 

Another option is to implement custom Jinja2 filters, so that you can generate advance formating options

**Comment by flying-sheep** [comment]
@ilan-gold check out the docs for Python’s string formatting syntax: https://docs.python.org/3/library/string.html#formatstrings

You escape braces like `{{` and `}}`, so you can just do ``fmt = '{{small}}`{thing}`'``, which gets rendered like this: ``fmt.format(thing=1) == '{small}`1`'``
