### ISSUE TITLE
'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by htgoebel** [twisted/towncrier#84]
Running towncrier without any config file crashes:
```
$ bin/pip install towncrier
$ bin/towncrier --draft
  File "/tmp/myvenv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/mvenv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/mvenv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/mvenv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/mvenv/lib/python2.7/site-packages/towncrier/__init__.py", line 38, in _main
    return __main(draft, directory, project_version, project_date, answer_yes)
  File "/tmp/mvenv/lib/python2.7/site-packages/towncrier/__init__.py", line 50, in __main
    if config['template'] is None:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by hawkowl** [comment]
Good catch. I'll fix this one for the next release, too.

**Comment by altendky** [comment]
The relocated `load_config()` can still return `None`.

https://github.com/twisted/towncrier/blob/ef1be451c44b71112cf6b6b2f1e90a27dd5ff489/src/towncrier/_settings.py#L55-L67

But it appears to be called only one place and have the `None` return handled now.

https://github.com/twisted/towncrier/blob/ef1be451c44b71112cf6b6b2f1e90a27dd5ff489/src/towncrier/_settings.py#L47-L50

It appears it was changed to a more descriptive error in 19.9.0rc1.

```bash
$ python3.9 -m venv venv

```
```bash
$ venv/bin/pip install --pre towncrier
Collecting towncrier
  Using cached towncrier-19.9.0rc1-py2.py3-none-any.whl (28 kB)
Processing /home/altendky/.cache/pip/wheels/f1/e3/67/f79591b232f0deb8e51317fa288eef8b996e2d6cf033bdc1a0/click_default_group-1.2.2-py3-none-any.whl
Collecting incremental
  Using cached incremental-17.5.0-py2.py3-none-any.whl (16 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting jinja2
  Using cached Jinja2-3.0.0a1-py3-none-any.whl (121 kB)
Processing /home/altendky/.cache/pip/wheels/5f/b9/dd/472dc449d66ee87116e227569d91c5a5a70d5288bbad1a4c77/MarkupSafe-2.0.0a1-cp39-cp39-linux_x86_64.whl
Collecting click
  Using cached click-8.0.0a1-py3-none-any.whl (89 kB)
Installing collected packages: MarkupSafe, click, toml, jinja2, incremental, click-default-group, towncrier
Successfully installed MarkupSafe-2.0.0a1 click-8.0.0a1 click-default-group-1.2.2 incremental-17.5.0 jinja2-3.0.0a1 toml-0.10.2 towncrier-19.9.0rc1
WARNING: You are using pip version 20.2.3; however, version 20.3.1 is available.
You should consider upgrading via the '/home/altendky/tmp/tmp/venv/bin/python3.9 -m pip install --upgrade pip' command.

```
```bash
$ venv/bin/towncrier build --draft
No configuration file found.
Looked in: /home/altendky/tmp/tmp
Traceback (most recent call last):
  File "/home/altendky/tmp/tmp/venv/bin/towncrier", line 8, in <module>
    sys.exit(cli())
  File "/home/altendky/tmp/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1025, in __call__
    return self.main(*args, **kwargs)
  File "/home/altendky/tmp/tmp/venv/lib/python3.9/site-packages/click/core.py", line 955, in main
    rv = self.invoke(ctx)
  File "/home/altendky/tmp/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1517, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/altendky/tmp/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1279, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/altendky/tmp/tmp/venv/lib/python3.9/site-packages/click/core.py", line 710, in invoke
    return callback(*args, **kwargs)
  File "/home/altendky/tmp/tmp/venv/lib/python3.9/site-packages/towncrier/build.py", line 63, in _main
    return __main(
  File "/home/altendky/tmp/tmp/venv/lib/python3.9/site-packages/towncrier/build.py", line 92, in __main
    base_directory, config = load_config_from_options(directory, config_file)
  File "/home/altendky/tmp/tmp/venv/lib/python3.9/site-packages/towncrier/_settings.py", line 48, in load_config_from_options
    raise ConfigError(
towncrier._settings.ConfigError: No configuration file found.
Looked in: /home/altendky/tmp/tmp

```

@htgoebel, are you comfortable closing this issue?  It looks to me to have been resolved, though it still needs a non-RC release.

**Comment by htgoebel** [comment]
Well, this still is ugly. This is a quite common and clearly defined error case. This should not 

I expect this case to quit with a clear but brief error message and *no* stacktrace.

**Comment by altendky** [comment]
@htgoebel, thanks for the prompt follow up.  Your comment makes sense to me and I'll go ahead and make a PR to implement it.
